# -*- coding: utf-8 -*-
"""Financial_Transactions_EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gthYL2NJYw0aVY7zsVJDaVuy5X6yVNyV

## About Dataset
With the rapid growth of digital banking and online transactions, financial institutions increasingly rely on data to understand transaction behavior, detect suspicious activities, and improve risk management.

This dataset contains transaction records that simulate real-world banking activity. It includes information about transaction details, customer demographics, device and channel metadata, as well as security-related indicators.

### Key Features:

- TransactionID: Unique alphanumeric identifier for each transaction.
- AccountID: Unique identifier for each account, with multiple transactions per account.
- TransactionAmount: Monetary value of each transaction, ranging from small everyday expenses to larger purchases.
- TransactionDate: Timestamp of each transaction, capturing date and time.
- TransactionType: Categorical field indicating 'Credit' or 'Debit' transactions.
- Location: Geographic location of the transaction, represented by U.S. city names.
- DeviceID: Alphanumeric identifier for devices used to perform the transaction.
- IP Address: IPv4 address associated with the transaction, with occasional changes for some accounts.
- MerchantID: Unique identifier for merchants, showing preferred and outlier merchants for each account.
- AccountBalance: Balance in the account post-transaction, with logical correlations based on transaction type and amount.
- PreviousTransactionDate: Timestamp of the last transaction for the account, aiding in calculating transaction frequency.
- Channel: Channel through which the transaction was performed (e.g., Online, ATM, Branch).
- CustomerAge: Age of the account holder, with logical groupings based on occupation.
- CustomerOccupation: Occupation of the account holder (e.g., Doctor, Engineer, Student, Retired), reflecting income patterns.
- TransactionDuration: Duration of the transaction in seconds, varying by transaction type.
- LoginAttempts: Number of login attempts before the transaction, with higher values indicating potential anomalies.
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import(accuracy_score, confusion_matrix,
classification_report, f1_score, roc_auc_score, average_precision_score)

from sklearn.decomposition import PCA
from sklearn.neighbors import LocalOutlierFactor

from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier, IsolationForest
from xgboost import XGBClassifier

import warnings
warnings.filterwarnings("ignore")

import gdown

# Fetch file id on Drive
file_id = "1fNiz9QRSD5drWAs3k1Ji09D_u3COOJWR"
url = f"https://drive.google.com/uc?export=download&id={file_id}"
gdown.download(url, "bank_transactions.csv", quiet=True)

# Load url
bank_df = pd.read_csv("bank_transactions.csv")

# Show first 5 rows
bank_df.head(5)

# Dataset size
bank_df.shape

# Check for misssing values
bank_df.isnull().sum()

# Check duplicated row
bank_df.duplicated().sum()

"""<br></br>

##### **Exploring column values**
"""

bank_df['LoginAttempts'].unique()

bank_df['CustomerOccupation'].unique()

bank_df['Channel'].unique()

bank_df['TransactionType'].unique()

# Total unique transaction duration
bank_df['TransactionDuration'].nunique()

# Total unique location
bank_df['Location'].nunique()

"""---

# **Exploratory Data Analysis**

#### Let's explore some major financial and behavioral patterns
"""

# Dataset info
bank_df.info()

# Summary statistics
bank_df[["AccountBalance", "TransactionAmount"]].describe().round(2)

# Min and Max values for transaction duration
print("******************************************************************")
print(f"The longest transaction duration spotted in banks was",bank_df['TransactionDuration'].max(), "seconds")
print("")
print(f"The smallest transaction duration spotted in banks was",bank_df['TransactionDuration'].min(), "seconds")
print("******************************************************************")

"""### **Let's investigate if customer's age play a role in transaction duration**"""

# Locate customers with longest transaction duration (300 seconds)
bank_df.loc[bank_df['TransactionDuration'] ==bank_df['TransactionDuration'].max()]

# Customer age who took exactly 300 seconds to complete a transaction
bank_df[bank_df['TransactionDuration'] == 300]['CustomerAge'].value_counts().reset_index()

# Locate customer with smallest transaction duration
bank_df[bank_df['TransactionDuration'] == 10]["CustomerAge"].value_counts().reset_index()

# View Customer age by average duration
bank_df.groupby('CustomerAge')['TransactionDuration'].mean().sort_values(ascending=False).head(10).reset_index()

"""## Comment:
Analysis of the longest transaction durations (300 seconds) revealed that  extended transaction times may be driven by specific customer behavior patterns rather than age demographics.

<br></br>

## **Visuals**
"""

# Visualize Account Balance distribution
plt.figure(figsize=(10,6))
plt.hist(data=bank_df, x="CustomerAge", bins=30, color="lightblue",edgecolor="black")
plt.title("Customer Age - Histogram", fontweight="bold")
plt.ylabel("Frequency")
plt.xlabel("Customer Age")
plt.gca().spines["top"].set_visible(False)
plt.gca().spines["right"].set_visible(False)

plt.show()

# Visualize Account Balance distribution
plt.figure(figsize=(10,6))
plt.hist(data=bank_df, x="AccountBalance", bins=30, color="blue",edgecolor="black")
plt.title("Account Balance - Histogram", fontweight="bold")
plt.ylabel("Frequency")
plt.xlabel("Account Balance")
plt.gca().spines["top"].set_visible(False)
plt.gca().spines["right"].set_visible(False)

plt.show()

# Visualize Transaction Amount distribution
plt.figure(figsize=(10,6))
plt.hist(data=bank_df, x="TransactionAmount", bins=30, color="green",edgecolor="black")
plt.title("Transaction Amount - Histogram", fontweight="bold")
plt.xlabel("Transaction Amount")
plt.gca().spines["top"].set_visible(False)
plt.gca().spines["right"].set_visible(False)
plt.show()

# Count each transaction type
type_counts = bank_df["TransactionType"].value_counts()

# Donut chart
plt.figure(figsize=(10,8))
plt.pie(type_counts.values, labels=type_counts.index, startangle=35, autopct='%1.1f%%', colors=sns.color_palette('Blues_r', len(type_counts)))
plt.gca().add_artist(plt.Circle((0,0), radius=0.8, fc='white'))
plt.title("Which Types of Transactions Occur Most Frequently?", fontweight='bold')
plt.show()

"""<br></br>"""

# Group Balance Account by customer occupation
cus_acc = bank_df.groupby("CustomerOccupation")["AccountBalance"].mean().sort_values(ascending=False).reset_index()

# Plot balance account by custumer occupation
plt.figure(figsize=(10,6))
sns.barplot(cus_acc, x ="CustomerOccupation", y ="AccountBalance", palette="YlGn_r", edgecolor="black")
plt.title("Which Customer Occupation Hold More Money in Bank Accounts", fontweight="bold")
plt.xlabel("Customer Occupation", fontsize =13)
plt.ylabel("")
plt.gca().spines["top"].set_visible(False)
plt.gca().spines["right"].set_visible(False)
plt.show()

# Group transaction amount by transaction type
transa_type = bank_df.groupby("TransactionType")["TransactionAmount"].mean().sort_values(ascending=False).reset_index()

# Plot average spending by transaction type
plt.figure(figsize=(10,6))
sns.barplot(transa_type, x ="TransactionType", y ="TransactionAmount", palette=["navy","blue"], edgecolor="turquoise")
plt.title("Average Spending Across Transaction Types", fontweight="bold")
plt.ylabel("")
plt.xlabel("Transaction Type", fontsize=13)
plt.gca().spines["top"].set_visible(False)
plt.gca().spines["right"].set_visible(False)
plt.show()

# Group transaction amount by Channel
transa_channel = bank_df.groupby("Channel")["TransactionAmount"].mean().sort_values(ascending=False).reset_index()

# Plot transaction amounts across channels
plt.figure(figsize=(10,6))
sns.barplot(transa_channel, x ="Channel", y ="TransactionAmount", palette="Blues_r", edgecolor="black")
plt.title("How Do Transaction Amounts Vary Across Channels", fontweight="bold")
plt.xlabel("Channel", fontsize =14)
plt.ylabel("")
plt.gca().spines["top"].set_visible(False)
plt.gca().spines["right"].set_visible(False)
plt.show()

# Group transaction amount by customer occupation
transa_occup = bank_df.groupby("CustomerOccupation")["TransactionAmount"].mean().sort_values(ascending=False).reset_index()

# Plot average spending by transaction type
plt.figure(figsize=(10,6))
sns.barplot(transa_occup, x ="CustomerOccupation", y ="TransactionAmount", palette="Reds_r", edgecolor="black")
plt.title("Average Spending Across Customer Occupation", fontweight="bold")
plt.ylabel("")
plt.xlabel("Customer Occupation")
plt.gca().spines["top"].set_visible(False)
plt.gca().spines["right"].set_visible(False)
plt.show()

# Group transaction amount by customer occupation
transa_occup = bank_df.groupby("Location")["TransactionAmount"].mean().sort_values(ascending=False).head(20).reset_index()

# Plot average spending by transaction type
plt.figure(figsize=(10,6))
sns.barplot(transa_occup, y ="Location", x ="TransactionAmount", palette="YlGn_r", edgecolor="lightblue")
plt.title("Top 20 Location with Most Average Spending", fontweight="bold")
plt.ylabel("")
plt.xlabel("Average Transaction Amount")
plt.gca().spines["top"].set_visible(False)
plt.gca().spines["right"].set_visible(False)
plt.show()

# Group transaction duration by channel
channel_dur = bank_df.groupby('Channel')['TransactionDuration'].mean().sort_values(ascending=False).reset_index()

# Plot
plt.figure(figsize=(10,6))
sns.barplot(channel_dur, x ="Channel", y ="TransactionDuration", palette="YlGn_r", edgecolor="lightblue")
plt.title("Which Channel Makes Transaction Longer?", fontweight="bold")
plt.ylabel("Average Transaction Duration (in seconds)")
plt.xlabel("Channel")
plt.gca().spines["top"].set_visible(False)
plt.gca().spines["right"].set_visible(False)
plt.show()

"""## Comment:
ATM transactions take longer than Online transactions, suggesting additional authentication or user interaction time.

<br></br>

#### **What Time of the Day Customers Transact Most?**
"""

# Date column transformation and feature engineering
bank_df['TransactionDate'] = pd.to_datetime(bank_df['TransactionDate'], format='mixed')
bank_df['Hour'] = bank_df['TransactionDate'].dt.hour

# Count the hours for transactions
hour_counts = (bank_df['Hour'].value_counts().sort_index().reset_index())

# Name tthe columns
hour_counts.columns = ['Hour', 'Transactions']

# Visualize
plt.figure(figsize=(10,6))
sns.barplot(data=hour_counts, x='Hour', y='Transactions',palette='YlGnBu_r', edgecolor='black')

plt.title('Transaction Activity by Hour of Day', fontsize=14,fontweight='bold')
plt.xlabel('Hour of Day')
plt.ylabel('Number of Transactions')

plt.xticks(rotation=0)
plt.gca().spines['top'].set_visible(False)
plt.gca().spines['right'].set_visible(False)
plt.tight_layout()
plt.show()

"""<br></br>"""

# Fetch only year in transaction date
bank_df['TransactionDate'] = pd.to_datetime(bank_df['TransactionDate'], format='mixed')
bank_df['Year'] = bank_df['TransactionDate'].dt.year

# Group account balances by year
transa_trend = bank_df.groupby("Year")["AccountBalance"].mean().reset_index()

# Plot trend
plt.figure(figsize=(10,6))
sns.lineplot(data=transa_trend, x="Year", y="AccountBalance", color="maroon")
plt.title("Average Account Balance Over Time", fontweight="bold")
plt.ylabel("")
plt.xlabel("Year", fontsize=13)
plt.gca().spines['top'].set_visible(False)
plt.gca().spines['right'].set_visible(False)
plt.tight_layout()
plt.show()

"""### Comment:
Account balances remained relatively stable between `$4.6K` and `$4.9K` over the six-year period. Overall, the account demonstrates stable liquidity.

---

# **Key Findings**

- Debit transactions dominate activity, accounting for 77.5% of all transactions.
- Credit and Debit transactions have similar average spending levels.
- Transaction amounts are consistent across ATM, Online, and Branch channels.
- Transaction duration shows minimal variation across channels.
- Transaction activity is concentrated at a single recorded hour, indicating a potential data pattern.
- Average account balances remain relatively stable, peaking in 2024.

- Austin and El Paso record the highest average transaction amounts.

- Students exhibit the highest average spending among occupations.

- Doctors maintain the highest average account balances.
"""