# -*- coding: utf-8 -*-
"""Anomaly Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zdli9xmlZPLCOdzapVUfJ0sc7J0qMDtf
"""

import seaborn as sns
import gdown
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.neighbors import LocalOutlierFactor
from sklearn.ensemble import IsolationForest

# Fetch file id on Drive
file_id = "1fNiz9QRSD5drWAs3k1Ji09D_u3COOJWR"
url = f"https://drive.google.com/uc?export=download&id={file_id}"
gdown.download(url, "bank_transactions.csv", quiet=True)

# Load url
bank_df = pd.read_csv("bank_transactions.csv")

"""#**Isolation Forest**
Business insight:

The model identified transactions that significantly differed from normal customer behavior in terms of amount, account balance, login attempts, and transaction duration.
"""

# Get variables for anomaly detection
features = ['AccountBalance','TransactionAmount','TransactionDuration','CustomerAge','LoginAttempts']

X= bank_df[features]

# Scale features
X_scaled = StandardScaler().fit_transform(bank_df[features])

# Build isolation forest mode l
model_iso = IsolationForest(contamination=0.002,random_state=42)
bank_df['Anomaly'] = model_iso.fit_predict(X_scaled)

# -1 = anomaly
# 1 = normal

# Visualize anomalies
pca = PCA(n_components=2)

X_pca = pca.fit_transform(X_scaled)

plt.figure(figsize=(10,6))
plt.scatter(X_pca[:,0], X_pca[:,1], c=bank_df['Anomaly'],cmap='cividis')

plt.title('Detected Anomalies', fontweight="bold")
plt.gca().spines['top'].set_visible(False)
plt.gca().spines['right'].set_visible(False)
plt.show()

# Show anomaly proportion
anomaly_pct = (bank_df['Anomaly'].value_counts(normalize=True).mul(100).round(2).reset_index(name='Percentage'))
anomaly_pct['Percentage'] = anomaly_pct['Percentage'].astype(str) + '%'

anomaly_pct

"""**The Isolation Forest model identified 0.19% of transactions as anomalies, while 99.81% were classified as normal.**

<br></br>

###**Local Outlier Factor**
"""

# Local Outlier Factor model
lof = LocalOutlierFactor(n_neighbors=20,contamination=0.002)

#
bank_df['lof_anomaly'] = lof.fit_predict(X_scaled)

lof_anomaly_pct = bank_df['lof_anomaly'].value_counts(normalize=True).mul(100).round(2).reset_index(name='Percentage')
lof_anomaly_pct['Percentage'] = lof_anomaly_pct['Percentage'].astype(str) + '%'

# Show anonaly percentage
lof_anomaly_pct

"""**The Local Outlier Factor (LOF) model identified 0.2% of transactions as anomalies, while 99.8% were classified as normal.**"""

# Glimpse of anomalies rows
anomalies = bank_df[bank_df['lof_anomaly'] == -1]
anomalies.head()

# Show anomaly table with normal activities
bank_df.groupby('lof_anomaly')[[ 'TransactionAmount', 'AccountBalance', 'CustomerAge','TransactionDuration','LoginAttempts']
                               ].mean().round(2).reset_index()

# Set PCA
pca = PCA(n_components=2)

X_pca = pca.fit_transform(X_scaled)

# Visualize LOF anomalies
plt.figure(figsize=(10,6))
plt.scatter(X_pca[:,0], X_pca[:,1], c=bank_df['lof_anomaly'],cmap='inferno')

plt.title('Detected Anomalies', fontweight="bold")
plt.gca().spines['top'].set_visible(False)
plt.gca().spines['right'].set_visible(False)
plt.show()

print("Comparing both methods:")
print("=======================================")
print("Isolation Forest:",(bank_df['Anomaly'] == -1).sum(),"anomalies")
print("Local Outlier Factor (LOF):", (bank_df['lof_anomaly'] == -1).sum(),"anomalies")

"""### Findings

Compared to normal observations, anomalies tend to have:

- Lower transaction amounts
- Higher average account balances
- Older customers
- Longer transaction durations
"""